import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function readRepoFile(relativePath: string) {
  return readFile(path.join(repoRoot, relativePath), "utf8");
}

function extractLocalLinkTargets(markdown: string): string[] {
  const linkPattern = /\[[^\]]+\]\(([^)]+)\)/g;
  const targets: string[] = [];
  for (const match of markdown.matchAll(linkPattern)) {
    const target = match[1];
    if (/^https?:\/\//i.test(target) || target.startsWith("mailto:")) {
      continue;
    }
    const withoutAnchor = target.split("#")[0];
    if (withoutAnchor.length > 0) {
      targets.push(withoutAnchor);
    }
  }
  return targets;
}

describe("README.md", () => {
  test("points to CONTRIBUTING.md for local development instead of duplicating setup steps", async () => {
    const readme = await readRepoFile("README.md");

    expect(readme).toContain("## Local Development");
    expect(readme).toContain("[CONTRIBUTING.md](CONTRIBUTING.md)");
    expect(readme).toContain("for setup, required checks, and pull-request requirements");
  });

  test("no longer duplicates the pnpm install/build/test instructions inline", async () => {
    const readme = await readRepoFile("README.md");
    const localDevSection = readme.slice(readme.indexOf("## Local Development"), readme.indexOf("## Notes"));

    expect(localDevSection).not.toContain("pnpm install");
    expect(localDevSection).not.toContain("pnpm build");
    expect(localDevSection).not.toContain("pnpm test");
    expect(localDevSection).not.toContain("OPENBRAIN_HOME");
    expect(localDevSection).not.toContain("CODEX_HOME");
  });

  test("all local markdown/asset links resolve to files that exist in the repo", async () => {
    const readme = await readRepoFile("README.md");
    const targets = extractLocalLinkTargets(readme);

    expect(targets.length).toBeGreaterThan(0);
    for (const target of targets) {
      await expect(
        access(path.join(repoRoot, target)),
        `expected README.md link target "${target}" to exist`
      ).resolves.toBeUndefined();
    }
  });
});

describe("CONTRIBUTING.md", () => {
  test("documents development setup using package.json-declared tooling", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");

    expect(contributing).toContain("## Development");
    expect(contributing).toContain("Use the Node.js and pnpm versions declared in `package.json`");
    expect(contributing).toContain("pnpm install --frozen-lockfile");
    expect(contributing).toContain("pnpm lint");
    expect(contributing).toContain("pnpm build");
    expect(contributing).toContain("pnpm test");
  });

  test("documented pnpm scripts exist in package.json", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");
    const packageJson = JSON.parse(await readRepoFile("package.json")) as {
      scripts?: Record<string, string>;
    };

    for (const script of ["lint", "build", "test"]) {
      expect(contributing).toContain(`pnpm ${script}`);
      expect(packageJson.scripts).toHaveProperty(script);
    }
  });

  test("tells contributors to isolate manual CLI testing from real state", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");

    expect(contributing).toContain("OPENBRAIN_HOME");
    expect(contributing).toContain("CODEX_HOME");
    expect(contributing).toContain("temporary directories");
  });

  test("lists issue and pull request expectations", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");

    expect(contributing).toContain("## Issues and pull requests");
    expect(contributing).toContain("Search existing issues and pull requests before opening a new one.");
    expect(contributing).toContain("Use a Conventional Commit title so release automation can classify the change.");
    expect(contributing).toContain(
      "Ensure `pnpm lint`, `pnpm build`, and `pnpm test` pass before requesting review."
    );
  });

  test("release versioning table covers any breaking-change type prefix, not just feat!:", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");

    expect(contributing).toContain("## Release versioning");
    expect(contributing).toContain("Any `<type>!:` or a `BREAKING CHANGE:` footer");
    expect(contributing).not.toContain("| `feat!:` or a `BREAKING CHANGE:` footer |");
  });

  test("clarifies that CHANGELOG.md is also generated by release automation", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");

    expect(contributing).toContain("Do not edit package versions or `CHANGELOG.md` manually");
    expect(contributing).toContain("CI prepares the version and changelog from the commit history");
    expect(contributing).not.toContain("Do not edit package versions manually.");
  });

  test("all local markdown link targets exist in the repo", async () => {
    const contributing = await readRepoFile("CONTRIBUTING.md");
    const targets = extractLocalLinkTargets(contributing);

    for (const target of targets) {
      await expect(
        access(path.join(repoRoot, target)),
        `expected CONTRIBUTING.md link target "${target}" to exist`
      ).resolves.toBeUndefined();
    }
  });
});